services:
  nginx-server:
    image: nginx:1.29-alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      server-1:
        condition: service_started
      server-2:
        condition: service_started
      server-3:
        condition: service_started
  mongo-server:
    image: mongo:8.0
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypassword
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--username",
          "myuser",
          "--password",
          "mypassword",
          "--authenticationDatabase",
          "admin",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  migration:
    image: migrate/migrate
    container_name: migration
    volumes:
      - ./server/internal/db/migrations:/migrations
      # Format: mongodb://user:pass@host:port/dbname?authSource=admin
    command:
      - -path=/migrations
      - -database=mongodb://myuser:mypassword@mongo-server:27017/movie_streaming?authSource=admin
      - up
    depends_on:
      mongo-server:
        condition: service_healthy
  server-1:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      mongo-server:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    env_file:
      - ./server/.env
    restart: always
  server-2:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      mongo-server:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    env_file:
      - ./server/.env
    restart: always
  server-3:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      mongo-server:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    env_file:
      - ./server/.env
    restart: always
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080/api/v1
    ports:
      - 80:80
    depends_on:
      server-1:
        condition: service_started
      server-2:
        condition: service_started
      server-3:
        condition: service_started
volumes:
  mongo-data:
